### ISSUE TITLE
#2 보안이슈 : 프로필 이미지 클라이언트 C드라이브 접근 제한 

### ISSUE THREAD

**Issue by MinCodeHub** [Hanium2023-WeB/starD-backend#12]
이미지를 수정해서 DB에서 이미지url을 받아오면 C:\\stard폴더에 이미지가 들어가는 것 까지는 확인했습니다.
![image](https://github.com/Hanium2023-WeB/starD-backend/assets/80142915/f12d438f-084d-47d8-b621-6901b331e71e)

그래서 화면에 이미지를 출력하기 위해 로컬 C드라이브에 접근을 해봤더니 
**보안상 문제로 클라이언트에서의 C드라이브 접근을 막아놓은 것 같습니다.  백엔드에서 url로 넘겨줘야한다고 하네요**
한번 확인부탁드립니다!!
![image](https://github.com/Hanium2023-WeB/starD-backend/assets/80142915/e4944ae7-ab32-441c-8988-9619723a18a0)
![image](https://github.com/Hanium2023-WeB/starD-backend/assets/80142915/0f39ddb7-cab6-499e-ab39-4e27df0d840d)

**Comment by rosieisor** [comment]
넵! 확인해보겠습니다! :)
