### ISSUE TITLE
프로젝트 디렉토리 구조 변경 

### ISSUE THREAD

**Issue by rosieisor** [Hanium2023-WeB/starD-backend#38]
저희 프로젝트 디렉토리 구조 보면 하나의 controller 폴더 안에 스터디, 사용자, 어드민 등등이 사용하는 게 모두 들어있어서 기능별이나 서비스 대상자 별로 구분해주는 게 좋을 것 같은데 어떻게 생각하시나요?!

**Comment by ckdmstn** [comment]
넵 좋습니다~!

**Comment by rosieisor** [comment]
![image](https://github.com/Hanium2023-WeB/starD-backend/assets/106025529/68722e61-21b4-4c16-80ca-ffeecb9f7c81)

이런 식으로 수정할까요?

domain 안에 member, admin, study 등등 넣으면 될 것 같아요!

참고문헌: https://velog.io/@jsb100800/Spring-boot-directory-package

**Comment by yslle** [comment]
좋아요!

**Comment by rosieisor** [comment]
제가 수정하고 pr 올릴게요!

**Comment by rosieisor** [comment]
master 브랜치에 병합 완료했습니다! 제가 임의로 domain 별로 구분한 거라, domain에 안맞는 파일이 있다면 변경해주셔도 괜찮아요~
